version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 792458513033.dkr.ecr.ap-northeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile -t frontend:cms-ims-nginx . --platform linux/amd64
      - docker tag frontend:cms-ims-nginx 792458513033.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:cms-ims-nginx
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 792458513033.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:cms-ims-nginx